spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

etl:
  startup:
    enabled: false

  single:
    enabled: true

  scheduler:
    enabled: false
    cron: "0 0 2 1 * *"
    zone: Africa/Tunis

app:
  datasource:
    erp:
      url: jdbc:postgresql://49.13.75.18:5432/rest_erp
      username: readonly_user
      password: strong_password
      driver-class-name: org.postgresql.Driver

    dw:
      url: jdbc:postgresql://localhost:5432/rest_erp_dw
      username: postgres
      password: Messaoud123!
      # password: Akef123*
      driver-class-name: org.postgresql.Driver